"""
Trend Engine for MODE_B Deep Learning Trend Following

Main orchestrator that combines:
- Technical Indicators (MA, Ichimoku, ATR)
- Ensemble Filter (DL + MA + Ichimoku)
- Position Manager (ATR trailing stop, time cut)
"""

import logging
import time
from dataclasses import dataclass
from typing import Dict, Optional, Tuple

from .technical_indicators import TechnicalCalculator, TechnicalData
from .ensemble_filter import EnsembleFilter, FilterResult
from .position_manager import (
    TrendPositionManager,
    TrendPosition,
    ExitSignal,
    ExitReason,
    PositionSide,
)

logger = logging.getLogger(__name__)


@dataclass
class TrendSignal:
    """Signal generated by TrendEngine"""
    timestamp: float
    action: str             # "OPEN_LONG", "OPEN_SHORT", "CLOSE", "HOLD"
    direction: Optional[str]  # "LONG", "SHORT", or None
    price: float            # Entry/exit price (best ask for buy, best bid for sell)
    size: float
    reason: str
    technical_data: Optional[TechnicalData] = None
    exit_reason: Optional[ExitReason] = None


class TrendEngine:
    """
    MODE_B Deep Learning Trend Following Engine

    Entry Flow:
    1. Check if no position exists
    2. Update technical indicators
    3. Check ensemble filter (DL + MA + Ichimoku)
    4. If all pass, open position

    Exit Flow (every tick):
    1. Update position tracking
    2. Check ATR trailing stop
    3. Check time cut (30 min)
    4. If triggered, close position
    """

    def __init__(
        self,
        dl_threshold: float = 0.85,
        ma_fast_period: int = 20,
        ma_slow_period: int = 60,
        atr_period: int = 14,
        atr_stop_multiplier: float = 2.0,
        time_cut_minutes: int = 30,
        time_cut_atr_threshold: float = 0.5,
        order_size: float = 1.0,
        min_bars_required: int = 60,
    ):
        """
        Args:
            dl_threshold: DL probability threshold (default 85%)
            ma_fast_period: Fast MA period (default 20)
            ma_slow_period: Slow MA period (default 60)
            atr_period: ATR period (default 14)
            atr_stop_multiplier: ATR multiplier for stop (default 2.0)
            time_cut_minutes: Minutes before time cut (default 30)
            time_cut_atr_threshold: Min favorable move as ATR multiple (default 0.5)
            order_size: Default order size (default 1.0)
            min_bars_required: Minimum bars before trading (default 60)
        """
        self.order_size = order_size
        self.min_bars_required = min_bars_required

        # Components
        self.technical = TechnicalCalculator(
            ma_fast_period=ma_fast_period,
            ma_slow_period=ma_slow_period,
            atr_period=atr_period,
        )

        self.ensemble_filter = EnsembleFilter(dl_threshold=dl_threshold)

        self.position_manager = TrendPositionManager(
            atr_stop_multiplier=atr_stop_multiplier,
            time_cut_minutes=time_cut_minutes,
            time_cut_atr_threshold=time_cut_atr_threshold,
        )

        # Last known prices for order execution
        self._last_bid: float = 0.0
        self._last_ask: float = 0.0

        # Statistics
        self._stats = {
            'total_checks': 0,
            'entries': 0,
            'exits': 0,
        }

    def update_prices(self, bid: float, ask: float):
        """Update current bid/ask prices for order execution."""
        self._last_bid = bid
        self._last_ask = ask

    def update_bar(self, high: float, low: float, close: float) -> TechnicalData:
        """
        Update with new bar data.

        Should be called on each new 1-minute bar.

        Args:
            high: Bar high
            low: Bar low
            close: Bar close

        Returns:
            Updated TechnicalData
        """
        return self.technical.update(high, low, close)

    def check(
        self,
        up_prob: float,
        current_price: float,
        symbol: str = "",
        timestamp: Optional[float] = None,
    ) -> TrendSignal:
        """
        Main check function - called on each tick/prediction.

        Handles both entry and exit logic.

        Args:
            up_prob: DL probability for up move
            current_price: Current market price
            symbol: Trading symbol
            timestamp: Current timestamp

        Returns:
            TrendSignal with action to take
        """
        self._stats['total_checks'] += 1
        timestamp = timestamp or time.time()

        # Get current technical data
        tech = self.technical.get_current_data()
        if tech is None:
            return TrendSignal(
                timestamp=timestamp,
                action="HOLD",
                direction=None,
                price=current_price,
                size=0,
                reason="Technical data not available",
            )

        current_atr = tech.atr

        # If we have a position, check for exit
        if self.position_manager.has_position:
            exit_signal = self.position_manager.update_and_check_exit(
                current_price=current_price,
                current_atr=current_atr,
                current_time=timestamp,
            )

            if exit_signal.should_exit:
                return self._create_exit_signal(exit_signal, timestamp, tech)

            # Position OK, hold
            return TrendSignal(
                timestamp=timestamp,
                action="HOLD",
                direction=self.position_manager.position_side.value,
                price=current_price,
                size=0,
                reason="Position held",
                technical_data=tech,
            )

        # No position - check for entry
        if not tech.is_ready:
            return TrendSignal(
                timestamp=timestamp,
                action="HOLD",
                direction=None,
                price=current_price,
                size=0,
                reason=f"Warming up: {len(self.technical.price_history)}/{self.min_bars_required} bars",
                technical_data=tech,
            )

        # Check ensemble filter
        filter_result = self.ensemble_filter.check_entry(up_prob, tech)

        if filter_result.can_enter:
            return self._create_entry_signal(
                filter_result=filter_result,
                tech=tech,
                symbol=symbol,
                timestamp=timestamp,
            )

        # No entry
        return TrendSignal(
            timestamp=timestamp,
            action="HOLD",
            direction=None,
            price=current_price,
            size=0,
            reason=filter_result.rejection_reason or "No signal",
            technical_data=tech,
        )

    def _create_entry_signal(
        self,
        filter_result: FilterResult,
        tech: TechnicalData,
        symbol: str,
        timestamp: float,
    ) -> TrendSignal:
        """Create entry signal and open position."""
        direction = filter_result.direction

        # Aggressive taker pricing
        if direction == "LONG":
            entry_price = self._last_ask if self._last_ask > 0 else tech.current_price
        else:  # SHORT
            entry_price = self._last_bid if self._last_bid > 0 else tech.current_price

        # Open position in position manager
        self.position_manager.open_position(
            side=direction,
            entry_price=entry_price,
            size=self.order_size,
            atr=tech.atr,
            symbol=symbol,
            timestamp=timestamp,
        )

        self._stats['entries'] += 1

        logger.info(
            f"MODE_B ENTRY: {direction} @ {entry_price:.2f}, "
            f"stop={self.position_manager.position.stop_price:.2f}, "
            f"ATR={tech.atr:.2f}"
        )

        return TrendSignal(
            timestamp=timestamp,
            action=f"OPEN_{direction}",
            direction=direction,
            price=entry_price,
            size=self.order_size,
            reason="Ensemble filter passed",
            technical_data=tech,
        )

    def _create_exit_signal(
        self,
        exit_signal: ExitSignal,
        timestamp: float,
        tech: TechnicalData,
    ) -> TrendSignal:
        """Create exit signal and close position."""
        pos = self.position_manager.position
        direction = pos.side.value

        # Use bid for selling long, ask for covering short
        if pos.is_long:
            exit_price = self._last_bid if self._last_bid > 0 else exit_signal.exit_price
        else:
            exit_price = self._last_ask if self._last_ask > 0 else exit_signal.exit_price

        # Close position
        pnl = self.position_manager.close_position(exit_price, exit_signal.reason)

        self._stats['exits'] += 1

        logger.info(
            f"MODE_B EXIT: {direction} @ {exit_price:.2f}, "
            f"PnL={pnl:.2f}, reason={exit_signal.reason.value}"
        )

        return TrendSignal(
            timestamp=timestamp,
            action="CLOSE",
            direction=direction,
            price=exit_price,
            size=pos.size,
            reason=exit_signal.message,
            technical_data=tech,
            exit_reason=exit_signal.reason,
        )

    def has_position(self) -> bool:
        """Check if there's an active position."""
        return self.position_manager.has_position

    def get_position_side(self) -> str:
        """Get current position side."""
        return self.position_manager.position_side.value

    def is_ready(self) -> bool:
        """Check if engine is ready for trading."""
        return self.technical.is_ready()

    def get_stats(self) -> dict:
        """Get engine statistics."""
        return {
            **self._stats,
            'technical': self.technical.get_stats(),
            'filter': self.ensemble_filter.get_stats(),
            'position': self.position_manager.get_stats(),
        }

    def reset(self):
        """Reset all state."""
        self.technical.reset()
        self.ensemble_filter.reset_stats()
        self.position_manager.reset()
        self._last_bid = 0.0
        self._last_ask = 0.0
        for key in self._stats:
            self._stats[key] = 0
