"""
Arbitrage Engine for MODE_A Sniper Basis Arbitrage

Entry Filters:
1. Time Filter - Use TradingHoursFilter (09:15-15:30, excluding lunch)
2. Dividend Blackout - No trading 14 days before quarterly expiry
3. Spread Filter - Enter only when spread <= 2 ticks
4. Depth Filter - Require bid/ask depth >= 5x order size
5. Basis Signal - Enter only when |basis_zscore| > 2.5σ
"""

import logging
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from typing import Dict, Optional, Tuple

from ..base import BarData
from .basis_calculator import BasisCalculator, BasisData

logger = logging.getLogger(__name__)


# KOSPI200 Mini Futures tick size
TICK_SIZE = 0.05


@dataclass
class ArbitrageSignal:
    """Signal generated by ArbitrageEngine"""
    timestamp: float
    direction: str           # "BUY" or "SELL"
    basis_zscore: float
    entry_price: float       # Best bid (BUY) or best ask (SELL)
    order_size: float
    basis_data: BasisData
    rejection_reason: Optional[str] = None


class ArbitrageEngine:
    """
    MODE_A Sniper Arbitrage Engine

    Pure statistical basis arbitrage with strict entry filters.
    No ML dependency - trades solely on basis deviation.
    """

    def __init__(
        self,
        max_spread_ticks: int = 2,
        depth_multiplier: float = 5.0,
        basis_threshold: float = 2.5,
        order_size: float = 5.0,
        quarterly_blackout_days: int = 14,
        risk_free_rate: float = 0.035,
        basis_rolling_window: int = 60,
    ):
        """
        Args:
            max_spread_ticks: Maximum spread in ticks for entry (default 2)
            depth_multiplier: Required depth as multiple of order size (default 5x)
            basis_threshold: Z-score threshold for entry (default 2.5σ)
            order_size: Default order size in contracts (default 5)
            quarterly_blackout_days: Days before quarterly expiry to avoid (default 14)
            risk_free_rate: Annual risk-free rate for fair value (default 3.5%)
            basis_rolling_window: Rolling window for z-score calculation (default 60)
        """
        self.max_spread_ticks = max_spread_ticks
        self.depth_multiplier = depth_multiplier
        self.basis_threshold = basis_threshold
        self.order_size = order_size
        self.quarterly_blackout_days = quarterly_blackout_days

        self.basis_calculator = BasisCalculator(
            risk_free_rate=risk_free_rate,
            rolling_window=basis_rolling_window,
        )

        # Time filter - lazy import to avoid circular dependency
        self._time_filter = None

        # Statistics
        self._stats = {
            'total_checks': 0,
            'passed': 0,
            'rejected_time': 0,
            'rejected_blackout': 0,
            'rejected_spread': 0,
            'rejected_depth': 0,
            'rejected_no_signal': 0,
            'rejected_not_ready': 0,
        }

    @property
    def time_filter(self):
        """Lazy load TradingHoursFilter to avoid import issues"""
        if self._time_filter is None:
            from ...backtest.filters import TradingHoursFilter
            self._time_filter = TradingHoursFilter()
        return self._time_filter

    def update_basis(
        self,
        spot_index: float,
        futures_price: float,
        days_to_expiry: int,
        timestamp: Optional[float] = None
    ) -> BasisData:
        """
        Update basis calculation with new market data.

        Args:
            spot_index: KOSPI200 index value
            futures_price: Futures mid price
            days_to_expiry: Days until contract expiry
            timestamp: Optional timestamp

        Returns:
            Updated BasisData
        """
        return self.basis_calculator.update(
            spot_index=spot_index,
            futures_price=futures_price,
            days_to_expiry=days_to_expiry,
            timestamp=timestamp
        )

    def check_entry(
        self,
        bar: BarData,
        spot_index: float,
        days_to_expiry: int,
        current_time: Optional[datetime] = None
    ) -> Tuple[bool, Optional[ArbitrageSignal], str]:
        """
        Check if entry conditions are met.

        Args:
            bar: Current market data (contains spread, depth, prices)
            spot_index: KOSPI200 index value
            days_to_expiry: Days until expiry
            current_time: Current datetime (default: now)

        Returns:
            (can_enter, signal, reason)
            - can_enter: True if all filters pass
            - signal: ArbitrageSignal if entry approved, None otherwise
            - reason: Explanation string
        """
        import time

        self._stats['total_checks'] += 1
        current_time = current_time or datetime.now()
        timestamp = time.time()

        # 1. Time Filter
        if not self.time_filter.can_open_position(current_time):
            self._stats['rejected_time'] += 1
            reason = self.time_filter.get_exclusion_reason(current_time) or "시간 외"
            return False, None, f"Time filter: {reason}"

        # 2. Dividend Blackout
        if self._is_dividend_blackout(current_time):
            self._stats['rejected_blackout'] += 1
            return False, None, "Dividend blackout period"

        # 3. Spread Filter
        spread_ticks = self._calculate_spread_ticks(bar.best_ask, bar.best_bid)
        if spread_ticks > self.max_spread_ticks:
            self._stats['rejected_spread'] += 1
            return False, None, f"Spread too wide: {spread_ticks} ticks > {self.max_spread_ticks}"

        # 4. Depth Filter
        min_depth = self.order_size * self.depth_multiplier
        if not self._check_depth(bar, min_depth):
            self._stats['rejected_depth'] += 1
            return False, None, f"Insufficient depth: need {min_depth} contracts"

        # 5. Update basis and check signal
        mid_price = (bar.best_bid + bar.best_ask) / 2
        basis_data = self.update_basis(spot_index, mid_price, days_to_expiry, timestamp)

        if not self.basis_calculator.is_ready():
            self._stats['rejected_not_ready'] += 1
            samples = len(self.basis_calculator.basis_history)
            return False, None, f"Basis calculator warming up: {samples}/{self.basis_calculator.min_samples}"

        has_signal, direction = self.basis_calculator.is_signal(self.basis_threshold)
        if not has_signal:
            self._stats['rejected_no_signal'] += 1
            z = basis_data.basis_zscore
            return False, None, f"No signal: z-score {z:.2f} within ±{self.basis_threshold}σ"

        # All filters passed - generate signal
        self._stats['passed'] += 1

        # Determine entry price (maker order)
        if direction == "BUY":
            entry_price = bar.best_bid  # Place limit at best bid
        else:  # SELL
            entry_price = bar.best_ask  # Place limit at best ask

        signal = ArbitrageSignal(
            timestamp=timestamp,
            direction=direction,
            basis_zscore=basis_data.basis_zscore,
            entry_price=entry_price,
            order_size=self.order_size,
            basis_data=basis_data,
        )

        logger.info(
            f"Arbitrage signal: {direction} @ {entry_price:.2f}, "
            f"z={basis_data.basis_zscore:.2f}σ, basis={basis_data.basis:.2f}"
        )

        return True, signal, f"Entry approved: {direction} @ {entry_price}"

    def _calculate_spread_ticks(self, ask: float, bid: float) -> int:
        """Calculate spread in number of ticks."""
        if ask <= 0 or bid <= 0:
            return 999  # Invalid prices
        spread = ask - bid
        return int(round(spread / TICK_SIZE))

    def _check_depth(self, bar: BarData, min_depth: float) -> bool:
        """
        Check if orderbook depth is sufficient.

        Uses bid/ask depth at levels 1-3.
        """
        # Sum depth at best 3 levels
        bid_depth = (
            getattr(bar, 'bid_qty1', 0) +
            getattr(bar, 'bid_qty2', 0) +
            getattr(bar, 'bid_qty3', 0)
        )
        ask_depth = (
            getattr(bar, 'ask_qty1', 0) +
            getattr(bar, 'ask_qty2', 0) +
            getattr(bar, 'ask_qty3', 0)
        )

        # Both sides must have sufficient depth
        return bid_depth >= min_depth and ask_depth >= min_depth

    def _is_dividend_blackout(self, dt: datetime) -> bool:
        """
        Check if in quarterly dividend blackout period.

        Blackout: 14 days before Mar/Jun/Sep/Dec expiry (2nd Thursday)
        """
        quarterly_months = [3, 6, 9, 12]

        # Find next quarterly expiry
        year = dt.year
        month = dt.month

        for qm in quarterly_months:
            if qm >= month:
                expiry = self._get_second_thursday(year, qm)
                if dt.date() <= expiry:
                    break
        else:
            # Next year's first quarter
            expiry = self._get_second_thursday(year + 1, 3)

        # Check if within blackout period
        blackout_start = expiry - timedelta(days=self.quarterly_blackout_days)
        return blackout_start <= dt.date() <= expiry

    def _get_second_thursday(self, year: int, month: int) -> date:
        """Get the 2nd Thursday of a given month."""
        first_day = date(year, month, 1)
        days_until_thursday = (3 - first_day.weekday()) % 7
        first_thursday = first_day + timedelta(days=days_until_thursday)
        second_thursday = first_thursday + timedelta(days=7)
        return second_thursday

    def get_stats(self) -> dict:
        """Get filter statistics."""
        return {
            **self._stats,
            'basis_stats': self.basis_calculator.get_stats(),
            'pass_rate': (
                self._stats['passed'] / self._stats['total_checks']
                if self._stats['total_checks'] > 0 else 0.0
            ),
        }

    def reset(self):
        """Reset state for new session."""
        self.basis_calculator.reset()
        for key in self._stats:
            self._stats[key] = 0


class DividendBlackoutChecker:
    """
    Standalone dividend blackout checker.

    Can be used independently of ArbitrageEngine.
    """

    QUARTERLY_MONTHS = [3, 6, 9, 12]

    def __init__(self, blackout_days: int = 14):
        self.blackout_days = blackout_days

    def is_blackout(self, dt: datetime) -> bool:
        """Check if date is in dividend blackout period."""
        year = dt.year
        month = dt.month

        for qm in self.QUARTERLY_MONTHS:
            if qm >= month:
                expiry = self._get_second_thursday(year, qm)
                if dt.date() <= expiry:
                    break
        else:
            expiry = self._get_second_thursday(year + 1, 3)

        blackout_start = expiry - timedelta(days=self.blackout_days)
        return blackout_start <= dt.date() <= expiry

    def get_next_blackout(self, dt: datetime) -> Tuple[date, date]:
        """Get next blackout period (start, end)."""
        year = dt.year
        month = dt.month

        for qm in self.QUARTERLY_MONTHS:
            if qm >= month:
                expiry = self._get_second_thursday(year, qm)
                blackout_start = expiry - timedelta(days=self.blackout_days)
                if dt.date() <= expiry:
                    return blackout_start, expiry

        # Next year
        expiry = self._get_second_thursday(year + 1, 3)
        blackout_start = expiry - timedelta(days=self.blackout_days)
        return blackout_start, expiry

    def _get_second_thursday(self, year: int, month: int) -> date:
        """Get the 2nd Thursday of a given month."""
        first_day = date(year, month, 1)
        days_until_thursday = (3 - first_day.weekday()) % 7
        first_thursday = first_day + timedelta(days=days_until_thursday)
        return first_thursday + timedelta(days=7)
