#!/bin/bash
# ============================================================
# KOSPI Mini Trading System - 서버 배포 스크립트
# Phase 8.4: 자동화된 배포
# ============================================================
#
# 사용법:
#   ./deploy_to_server.sh                    # 기본 배포
#   ./deploy_to_server.sh --with-monitoring  # 모니터링 포함
#   ./deploy_to_server.sh --infra-only       # 인프라만 (Redis, ClickHouse)
#   ./deploy_to_server.sh --stop             # 서비스 중지
#
# 환경변수 (필수):
#   DEPLOY_HOST: 배포 대상 서버 (예: user@server.com)
#   KIS_APP_KEY: 한투 API 키
#   KIS_APP_SECRET: 한투 API 시크릿
#
# 환경변수 (선택):
#   DEPLOY_PATH: 원격 서버 경로 (기본: ~/trading-system)
#   FUTURES_CODE: 선물 코드 (기본: 자동 계산)

set -e

# 색상 정의
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# 기본값
DEPLOY_PATH="${DEPLOY_PATH:-~/trading-system}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 로그 함수
log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# 도움말
show_help() {
    cat << EOF
KOSPI Mini Trading System 배포 스크립트

사용법:
    ./deploy_to_server.sh [옵션]

옵션:
    --with-monitoring   Prometheus + Grafana 포함 배포
    --infra-only        인프라만 배포 (Redis, ClickHouse)
    --stop              모든 서비스 중지
    --logs              로그 확인
    --status            서비스 상태 확인
    -h, --help          도움말

환경변수:
    DEPLOY_HOST         배포 대상 서버 (필수)
    KIS_APP_KEY         한투 API 키 (필수)
    KIS_APP_SECRET      한투 API 시크릿 (필수)
    DEPLOY_PATH         원격 경로 (기본: ~/trading-system)
    FUTURES_CODE        선물 코드 (기본: 자동)
    DRY_RUN             테스트 모드 (기본: true)

예시:
    # 환경변수 설정 후 배포
    export DEPLOY_HOST="user@myserver.com"
    export KIS_APP_KEY="your_key"
    export KIS_APP_SECRET="your_secret"
    ./deploy_to_server.sh --with-monitoring
EOF
}

# 환경변수 검증
check_env() {
    if [ -z "$DEPLOY_HOST" ]; then
        log_error "DEPLOY_HOST 환경변수가 설정되지 않았습니다."
        exit 1
    fi

    if [ -z "$KIS_APP_KEY" ] || [ -z "$KIS_APP_SECRET" ]; then
        log_warn "KIS_APP_KEY 또는 KIS_APP_SECRET이 설정되지 않았습니다."
        log_warn "틱 수집기가 작동하지 않을 수 있습니다."
    fi
}

# 소스 코드 동기화
sync_code() {
    log_info "소스 코드 동기화 중... ($DEPLOY_HOST:$DEPLOY_PATH)"

    rsync -avz --delete \
        --exclude '.git' \
        --exclude '__pycache__' \
        --exclude '*.pyc' \
        --exclude '.pytest_cache' \
        --exclude 'venv' \
        --exclude '.venv' \
        --exclude '*.egg-info' \
        --exclude 'models/*.pth' \
        --exclude 'dist' \
        --exclude 'build' \
        "$SCRIPT_DIR/" "$DEPLOY_HOST:$DEPLOY_PATH/"

    log_info "동기화 완료"
}

# 환경 파일 생성
create_env_file() {
    log_info ".env 파일 생성 중..."

    # 로컬에서 .env 파일 생성
    cat > /tmp/.env.deploy << EOF
# KOSPI Mini Trading System Configuration
# Generated by deploy_to_server.sh

# 한국투자증권 API
KIS_APP_KEY=${KIS_APP_KEY:-}
KIS_APP_SECRET=${KIS_APP_SECRET:-}
KIS_MARKET=${KIS_MARKET:-real}
KIS_ACCOUNT_NO=${KIS_ACCOUNT_NO:-}

# 선물 코드 (빈 값이면 자동 계산)
FUTURES_CODE=${FUTURES_CODE:-}

# 트레이딩 설정
DRY_RUN=${DRY_RUN:-true}
STRATEGY=${STRATEGY:-pure_micro}

# ClickHouse
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-}

# Grafana (모니터링 사용 시)
GRAFANA_USER=${GRAFANA_USER:-admin}
GRAFANA_PASSWORD=${GRAFANA_PASSWORD:-admin}
EOF

    scp /tmp/.env.deploy "$DEPLOY_HOST:$DEPLOY_PATH/.env"
    rm /tmp/.env.deploy

    log_info ".env 파일 생성 완료"
}

# Docker Compose 실행
run_docker_compose() {
    local cmd=$1
    shift
    local extra_args="$@"

    ssh "$DEPLOY_HOST" "cd $DEPLOY_PATH && docker compose $cmd $extra_args"
}

# 배포 - 인프라만
deploy_infra() {
    log_info "인프라 배포 중 (Redis, ClickHouse)..."
    run_docker_compose "up -d redis clickhouse"
    log_info "인프라 배포 완료"
}

# 배포 - 전체
deploy_all() {
    log_info "전체 서비스 배포 중..."
    run_docker_compose "up -d --build"
    log_info "전체 배포 완료"
}

# 배포 - 모니터링 포함
deploy_with_monitoring() {
    log_info "모니터링 포함 배포 중..."
    run_docker_compose "up -d --build --profile monitoring"
    log_info "모니터링 포함 배포 완료"
}

# 서비스 중지
stop_services() {
    log_info "서비스 중지 중..."
    run_docker_compose "down"
    log_info "서비스 중지 완료"
}

# 서비스 상태
show_status() {
    log_info "서비스 상태:"
    run_docker_compose "ps"
}

# 로그 확인
show_logs() {
    local service=${1:-}
    if [ -n "$service" ]; then
        run_docker_compose "logs -f $service"
    else
        run_docker_compose "logs -f"
    fi
}

# 메인
main() {
    local action="deploy"
    local with_monitoring=false

    # 인자 파싱
    while [[ $# -gt 0 ]]; do
        case $1 in
            --with-monitoring)
                with_monitoring=true
                shift
                ;;
            --infra-only)
                action="infra"
                shift
                ;;
            --stop)
                action="stop"
                shift
                ;;
            --status)
                action="status"
                shift
                ;;
            --logs)
                action="logs"
                shift
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                log_error "알 수 없는 옵션: $1"
                show_help
                exit 1
                ;;
        esac
    done

    # 환경변수 확인
    check_env

    case $action in
        deploy)
            sync_code
            create_env_file
            if [ "$with_monitoring" = true ]; then
                deploy_with_monitoring
            else
                deploy_all
            fi
            show_status
            ;;
        infra)
            sync_code
            create_env_file
            deploy_infra
            show_status
            ;;
        stop)
            stop_services
            ;;
        status)
            show_status
            ;;
        logs)
            show_logs
            ;;
    esac

    log_info "완료!"
}

main "$@"
